version: '3.9'

services:
  api:
    # container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000

